//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFrameworkEntityApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public int Stationery { get; set; }
        public int Count { get; set; }
        public int Manager { get; set; }
        public int BuyerFirm { get; set; }
        public System.DateTime Date { get; set; }
    }
}
