//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFrameworkEntityApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stationery
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int Count { get; set; }
        public int CostPrice { get; set; }
        public int UnitPrice { get; set; }
    }
}
