//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFrameworkEntityApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StationeryFirmEntities : DbContext
    {
        public StationeryFirmEntities()
            : base("name=StationeryFirmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuyerFirm> BuyerFirms { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Stationery> Stationeries { get; set; }
        public virtual DbSet<StationeryType> StationeryTypes { get; set; }
    }
}
